import { s as subscribe } from "../../../chunks/utils.js";
import { c as create_ssr_component, b as escape, a as add_attribute, e as each, v as validate_component } from "../../../chunks/ssr.js";
import { b as bibleStore, L as LoadingModal } from "../../../chunks/LoadingModal.js";
import { u as uiStore } from "../../../chunks/uiStore.js";
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let $bibleStore, $$unsubscribe_bibleStore;
  let $uiStore, $$unsubscribe_uiStore;
  $$unsubscribe_bibleStore = subscribe(bibleStore, (value) => $bibleStore = value);
  $$unsubscribe_uiStore = subscribe(uiStore, (value) => $uiStore = value);
  let { data } = $$props;
  if ($$props.data === void 0 && $$bindings.data && data !== void 0)
    $$bindings.data(data);
  $$unsubscribe_bibleStore();
  $$unsubscribe_uiStore();
  return `<div class="bg-base-200 h-full relative pt-5 md:px-7"><div class="border-b border-b-white flex justify-between items-center px-7 pb-3"><p class="text-white font-semibold text-sm md:text-base lg:text-lg xl:text-xl"><span>${escape($bibleStore.openChapter.bookName)}</span> <span>${escape($bibleStore.openChapter.number)}</span></p> <div class="search-bar join w-[70%] md:w-[50%] flex justify-center"><input class="input input-bordered join-item input-xs lg:input-sm w-[100%] md:w-[70%]" placeholder="Search the entire bible" type="search"> <button class="btn btn-primary join-item rounded-r-full btn-xs lg:btn-sm" data-svelte-h="svelte-j94aiw">search</button></div>   <div class="md:hidden" data-svelte-h="svelte-cqtdur"><img src="/menu.svg" alt="" srcset=""></div> <div class="hidden items-center md:flex"><div class="font-customize flex items-center"><button class="btn mx-1 btn-xs btn-circle btn-outline btn-primary" data-svelte-h="svelte-1pbj2u3"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" stroke="currentColor"><path d="M19,13H5V11H19V13Z"></path></svg></button> <button class="btn btn-xs mx-1 btn-circle btn-outline btn-primary" data-svelte-h="svelte-nb9r3q"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" stroke="currentColor"><path d="M19,13H13V19H11V13H5V11H11V5H13V11H19V13Z"></path></svg></button></div> <select${add_attribute("value", $bibleStore.bibleVersion?.toUpperCase(), 0)} class="select select-primary select-xs lg:select-sm w-full max-w-xs mx-2"><option value="ESV" data-svelte-h="svelte-18f74xi">English Standard Version (ESV) </option><option value="KJV" data-svelte-h="svelte-wnu93i">King James Version</option><option value="NASB" data-svelte-h="svelte-1udzx7k">New American Standard Bible (NASB)</option><option value="NLT" data-svelte-h="svelte-eikeiv">New Living Translation (NLT)</option><option value="RSV" data-svelte-h="svelte-1ivx61c">Revised Standard Version (RSV)</option></select> <button class="btn btn-primary btn-xs lg:btn-sm" data-svelte-h="svelte-1ofoz5x">Quiz</button></div></div> ${data?.verses?.length ? `<div class="menu rounded-box overflow-y-auto max-h-[90vh]"><ul>${each(data.verses, (verse, index) => {
    return `  <li${add_attribute("id", `verse${verse.verse}`, 0)}><p class="text-[#a6adba] leading-10"${add_attribute("style", `font-size: ${$uiStore.chapterFontSize}px`, 0)}>${escape(verse.verse)} ${escape(verse.text)}</p> </li>`;
  })} </ul></div>` : ``} ${$bibleStore.openChapter.loading ? `${validate_component(LoadingModal, "LoadingModal").$$render($$result, {}, {}, {})}` : ``} ${data.verses?.length ? `<div class="chapter-controls absolute bottom-[9%] md:bottom-3 left-0 flex items-center w-full justify-center z-10"><div class="flex items-center bg-base-100 justify-center p-2 rounded-full shadow-xl"><button class="btn btn-sm mx-3 btn-circle btn-outline btn-primary" data-svelte-h="svelte-y5mety"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="h-5 w-5" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 12H5M12 5l-7 7 7 7"></path></svg></button>   <div class="md:hidden" data-svelte-h="svelte-1dx8bnj"><img src="/settings.svg" alt="" srcset=""></div> <button class="btn btn-sm mx-3 btn-circle btn-outline btn-primary" data-svelte-h="svelte-y3whi5"><svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M12 5l7 7-7 7"></path></svg></button></div></div>` : ``}</div>`;
});
export {
  Page as default
};
